name: Read PR Template Details

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    # types:
    #   - closed
    # branches: [ 'development' ]

jobs:
  extract-pr-template:
    # if: github.event.label.name=='template-updated'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # - name: Set up GitHub CLI
      #   run: |
      #     echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      # - name: Fetch PR details
      #   id: pr-details
      #   run: |
      #     gh pr view ${{ github.event.pull_request.number }} --json body -q .body > pr_body.txt
      #     PR_BODY=$(cat pr_body.txt)
      #     echo "Fetched PR Body: $PR_BODY"
      - name: Parse and Validate PR Body
        id: parse_pr
        run: |
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")
          echo "PR_BODY=$PR_BODY"
          
          # Extract image tags from the PR description
          DEV_AP=$(echo "$PR_BODY" | grep -A 3 "Dev Environment" | grep "AP Region:" | awk -F'`' '{print $2}')          
          DEV_EU=$(echo "$PR_BODY" | grep -A 3 "Dev Environment" | grep "EU Region:" | awk -F'`' '{print $2}')
          DEV_US=$(echo "$PR_BODY" | grep -A 3 "Dev Environment" | grep "US Region:" | awk -F'`' '{print $2}') 
          echo "DEV_AP=$DEV_AP" >> $GITHUB_ENV
          echo "DEV_EU=$DEV_EU" >> $GITHUB_ENV
          echo "DEV_US=$DEV_US" >> $GITHUB_ENV

          echo "Extracted Image Tags:"
          echo "AP Region: $DEV_AP"
          echo "EU Region: $DEV_EU"
          echo "US Region: $DEV_US"
          
      - name: Print image tags for debugging
        run: |
          echo "AP Region: $DEV_AP"
          echo "EU Region: $DEV_EU"
          echo "US Region: $DEV_US"
      
